export var blogssData = [
  {
    id: 1,
    bgColor: "#FCD5E4",
    name: "Team Noor",
    title: `Why your friend ≠ a therapist`,
    label: "label",
    date: "27 aug 2021",
    bgUrl: "/assets/images/Blog/Blog1.jpg",
    link: "/blogs/1",
  },
  {
    id: 2,
    bgColor: "#AAF1DB",
    name: "Team Noor",
    title: "Counselling or therapy? Are they the same?",
    label: "label",
    date: "28 aug 2021",
    bgUrl:
      "https://images.unsplash.com/photo-1510739859545-e7b9e979de86?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=667&q=80",
    link: "/blogs/2",
  },
  {
    id: 3,
    bgColor: "#C1E1FF",
    name: "Team Noor",
    title: `Choosing a psychologist`,
    label: "label",
    date: "29 aug 2021",
    bgUrl: "https://picsum.photos/id/1015/1000/600/",
    link: "/blogs/3",
  },
  {
    id: 3,
    bgColor: "#C1E1FF",
    name: "Manaswi",
    title: `Happy international men's day`,
    label: "label",
    date: "19 Nov 2021",
    bgUrl: "https://i.imgur.com/XPUb2I6.png",
    link: "/blogs/4",
  },
]
