import React, { useState, useEffect } from "react"
import Head from "next/head"
import Image from "next/image"
import styles from "./home.module.css"
import styles1 from "./events/eventdetails/event_details.module.css"
import cx from "classnames"
import Footer from "../components/footer"
import { BsCircle, BsCircleFill } from "react-icons/bs"

export default function Home() {
  const impressions = [
    {
      id: 1,
      img: "/assets/images/avatarHuman.png",
      name: "JOHN DOE",
      event: "Attended X event",
      review:
        "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no.",
    },
    {
      id: 2,
      img: "/assets/images/avatarHuman.png",
      name: "JOHN DOE",
      event: "Attended Y event",
      review:
        "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no.",
    },
    {
      id: 3,
      img: "/assets/images/avatarHuman.png",
      name: "JOHN DOE",
      event: "Attended Z event",
      review:
        "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no.",
    },
  ]

  const [activeCard, setactiveCard] = useState(0)
  const [translateX, setTranslateX] = useState(0)
  var activeWindowSize = 1080

  const setCard = (index) => {
    let multiplier = activeCard - index
    setactiveCard(() => index)
    const card = document.getElementById("card")
    setTranslateX(() => translateX + multiplier * (card.offsetWidth + 480))
  }

  const handleResize = () => {
    if (window.innerWidth < 650 && window.innerWidth > 520 && activeWindowSize != 650) {
      activeWindowSize = 650
      setactiveCard(0)
      setCard(0)
    }
    if (window.innerWidth < 520 && activeWindowSize != 520) {
      activeWindowSize = 520
      setactiveCard(0)
      setCard(0)
    }
  }

  useEffect(() => {
    window.addEventListener("resize", handleResize)
    return () => window.removeEventListener("resize", handleResize)
  })

  return (
    <div>
      <Head>
        <title>Noor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.home_wrapper}>
        <main>
          <section>
            <div className={styles.heading}>
              <div style={{ textAlign: "center", alignItems: "center" }}>What is Noor?</div>
            </div>
            <div className={styles._noor_bg_container}>
              <img className={styles.noor_bg_img} src="/assets/images/Utils/Background_noor.png" alt="" />
            </div>
          </section>
          <section className={styles.transformation}>
            <div className={styles.heading}>
              <div style={{ textAlign: "center", alignItems: "center" }}>
                <div className={styles.inner_heading}>Here's what's new</div>
                <img className={styles.inner_img} src="/assets/images/Utils/BackgroundHeading2.png" alt="" />
              </div>
            </div>
            <div className={cx(styles.whats_new_bg_container, styles.bg_container_1)}>
              <section className={styles1.impressions_home}>
                <div className={cx(styles1.cards_container, styles.whats_new_cards_container)}>
                  {impressions.map((impression) => (
                    <div
                      className={cx(styles1.card, styles.whats_new_card)}
                      key={impression.id}
                      id="card"
                      style={{ transform: `translateX(${translateX}px)` }}
                    >
                      <div className={styles.new_img_container}>
                        <img src="/assets/images/WhatsNew-PlaceHolders/img_placeholder.png" alt="" />
                      </div>
                      <div className={styles.whats_new_content}>
                        <div className={styles.label}>New Event</div>
                        <div className={styles.event_name}>New Event</div>
                        <div className={styles.event_details}>
                          Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna
                          aliquyam erat, sed diam voluptua.{" "}
                        </div>
                        <button className={styles.register_button}>Seek Help</button>
                      </div>
                    </div>
                  ))}
                </div>
                <div className={cx(styles1.active_buttons, styles.active_buttons)} style={{ transform: "TranslateY(-20px)" }}>
                  {impressions.map((count, index) => {
                    return index === activeCard ? (
                      <div style={{ marginRight: index !== impressions.length ? "1.2rem" : "0px", color: "#707070", cursor: "pointer" }}>
                        <BsCircleFill
                          onClick={() => {
                            setCard(index)
                          }}
                        />
                      </div>
                    ) : (
                      <div style={{ marginRight: index !== impressions.length ? "1.2rem" : "0px", color: "#ffffff", cursor: "pointer" }}>
                        <BsCircleFill
                          onClick={() => {
                            setCard(index)
                          }}
                        />
                      </div>
                    )
                  })}
                </div>
              </section>
            </div>
            <div className={styles.see_all_events}>See all events</div>
          </section>
          <section className={styles.transformation2}>
            <div className={styles.heading}>
              <div style={{ textAlign: "center", alignItems: "center" }}>
                <div className={styles.inner_heading}>Here's what's old</div>
                <img className={styles.inner_img} src="/assets/images/Utils/BackgroundHeading2.png" alt="" />
              </div>
            </div>
            <div className={cx(styles.whats_new_bg_container, styles.bg_container_2)} style={{ flexDirection: "column", height: "50rem" }}>
              <div className={styles.graphic_container}>
                <div className={styles.left_holder}>
                  <div className={styles.left_large}>
                    <img src="/assets/images/WhatsOld-Placeholders/LeftLarge1.png" alt="" />
                  </div>
                  <div className={styles.left_small}>
                    <div className={styles.left_left}>
                      <div className={styles.left_small_img}>
                        <img src="/assets/images/WhatsOld-Placeholders/LeftSmallImage1.png" alt="" />
                      </div>
                      <div className={styles.left_small_img}>
                        <img src="/assets/images/WhatsOld-Placeholders/LeftSmallImage1.png" alt="" />
                      </div>
                    </div>
                    <div className={styles.right_right}>
                      <div className={styles.left_small_img}>
                        <img src="/assets/images/WhatsOld-Placeholders/LeftSmallImage1.png" alt="" />
                      </div>
                      <div className={styles.left_small_img}>
                        <img src="/assets/images/WhatsOld-Placeholders/LeftSmallVideo1.png" alt="" />
                      </div>
                    </div>
                  </div>
                </div>
                <div className={styles.right_holder}>
                  <img src="/assets/images/WhatsOld-Placeholders/RightImg1.png" alt="" srcset="" />
                </div>
              </div>
              <div className={styles.old_content}>
                <div className={styles.old_content_name}>Event Name</div>
                <div className={styles.old_content_text}>
                  Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna{" "}
                  <span className={styles.hide}>
                    {" "}
                    aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea
                    takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
                    tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
                  </span>
                </div>
              </div>
              <div className={styles.line}></div>
            </div>
          </section>
          <section className={styles.transformation3}>
            <div className={styles.heading}>
              <div style={{ textAlign: "center", alignItems: "center" }}>
                <div className={styles.inner_heading}>Looking for help?</div>
                <img className={styles.inner_img} src="/assets/images/Utils/BackgroundHeading2.png" alt="" />
              </div>
            </div>
            <div className={cx(styles.whats_new_bg_container, styles.bg_container_3)} style={{ height: "35rem" }}>
              <div className={styles.help_text} style={{ transform: "translateY(-40px)" }}>
                Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam
                erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus
                est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr
                <span className={styles.hide}>
                  sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo
                  duo dolores et ea
                </span>
              </div>
            </div>
            <div className={styles.seekHelp_bg}>
              <img src="/assets/images/Utils/SeekHelp.png" alt="" />
            </div>
            <button className={styles.seekHelp_button}>Seek Help</button>
          </section>
          <section className={styles.they_think}>
            <div className={styles.heading}>
              <div style={{ textAlign: "center", alignItems: "center" }}>They think we're nice</div>
            </div>
            <section className={cx(styles1.impressions, styles.impressions)}>
              <div className={cx(styles1.cards_container, styles.whats_new_cards_container)}>
                {impressions.map((impression) => (
                  <div className={styles1.card} key={impression.id} id="card" style={{ transform: `translateX(${translateX}px)` }}>
                    <div className={styles1.person}>
                      <div className={styles1.avatar}>
                        <img src={impression.img} alt={impression.img} />
                      </div>
                      <div className={cx(styles1.nameAndEvent, styles.nameAndEvent)}>
                        <h1>{impression.name}</h1>
                        <p>{impression.event}</p>
                      </div>
                    </div>
                    <div className={styles1.review}>{impression.review}</div>
                  </div>
                ))}
              </div>
              <div className={cx(styles1.active_buttons, styles.active_buttons_2)}>
                {impressions.map((count, index) => {
                  return index === activeCard ? (
                    <div style={{ marginRight: index !== impressions.length ? "1.2rem" : "0px", color: "#707070", cursor: "pointer" }}>
                      <BsCircleFill
                        onClick={() => {
                          setCard(index)
                        }}
                      />
                    </div>
                  ) : (
                    <div style={{ marginRight: index !== impressions.length ? "1.2rem" : "0px", color: "#ffffff", cursor: "pointer" }}>
                      <BsCircleFill
                        onClick={() => {
                          setCard(index)
                        }}
                      />
                    </div>
                  )
                })}
              </div>
            </section>
          </section>

          <section className={styles.transformation4}>
            <div className={styles.heading}>
              <div style={{ textAlign: "center", alignItems: "center" }}>
                <div className={styles.inner_heading}>Institutional Reach</div>
                <img className={styles.inner_img} src="/assets/images/Utils/BackgroundHeading2.png" alt="" />
              </div>
            </div>
            <div className={cx(styles.whats_new_bg_container, styles.bg_container_4)} style={{ height: "30rem" }}>
              <div className={styles.institutional_text}>
                Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam
                erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus
                est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet
                <div className={styles.absolute_hyperLink}>Check out Institutes</div>
              </div>
            </div>
          </section>
        </main>
      </section>
    </div>
  )
}
